apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 0.5Gi