apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  namespace: cloudchamp
spec:
  containers:
    - name: mongodb-container
      image: mongo
      volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
  volumes:
    - name: mongodb-persistent-storage
      persistentVolumeClaim:
        claimName: mongodb-persistent-storage-claim